# Generated by Django 5.2.12 on 2026-05-22 17:13

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_account_status_user_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.PlatformUserManager()),
            ],
        ),
    ]
